- title: "중년 게이머 연구"
  article_link: "http://tgsi.or.kr/reference/6"
  year: "11, 2022 - 04,2023"
  dev_tool:
    - "게임이에여"
    - "뭐지"
    - "엥"
  abstract: "멘트 알아서 수정하시길..."
  image: "../assets/images/Thumbnail/MiddleAgedGamerStudy.png" 
